name: Debian

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-arch64:
    runs-on: ubuntu-latest
    container: symless/synergy-core:${{ matrix.distro }}
    continue-on-error: true
    env:
      GIT_COMMIT: ${{ github.sha }}
    strategy:
      matrix:
        include:
          - distro: debian9
          - distro: debian10
          - distro: debian11

    name: ${{ matrix.distro }}

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"
          fetch-depth: "0"

      - name: Install rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: cargo, rustc, rust-std

      - name: Build
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release ..
          . ./version
          make -j

      - name: Run unit test
        run: ./build/bin/unittests
