name: Fedora

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    paths:
      - src/**
      - .gitmodules
      - CMakeLists.txt

jobs:
  build-arch64:
    runs-on: ubuntu-latest
    container: symless/synergy-core:fedora${{ matrix.distro }}

    strategy:
      matrix:
        distro: ["33", "34", "35", "36"]

    env:
      GIT_COMMIT: ${{ github.sha }}

    name: fedora${{ matrix.distro }}

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX:PATH=$(pwd)/rpm/BUILDROOT/usr ..
          . ./version
          make -j

      - name: Run unit test
        run: ./build/bin/unittests
